config/routes.rb
Rails.application.routes.draw do
  resources :nodes
  root "hello#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/node.rb
class Node < ApplicationRecord
  has_closure_tree
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: %i[ show edit update destroy ]

  # GET /nodes or /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1 or /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes or /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to node_url(@node), notice: "Node was successfully created." }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1 or /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to node_url(@node), notice: "Node was successfully updated." }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1 or /nodes/1.json
  def destroy
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url, notice: "Node was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def node_params
      params.require(:node).permit(:name, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/hello/index.html.erb
<div class="App">
  <header class="App-header">
    <img src="Octocat.png" class="App-logo" alt="logo" />
    <p>
      GitHub Codespaces <span class="heart">♥️</span> Rails
    </p>
    <p class="small">
      Edit <code>app/views/hello/index.html.erb</code> and see changes live!
    </p>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodespacesTryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/_form.html.erb
<%= form_with(model: node) do |form| %>
  <% if node.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
        <% node.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :parent_id, style: "display: block" %>
    <%= form.number_field :parent_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nodes/_node.html.erb
<div id="<%= dom_id node %>">
  <p>
    <strong>Name:</strong>
    <%= node.name %>
  </p>

  <p>
    <strong>Parent:</strong>
    <%= node.parent_id %>
  </p>

</div>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render "form", node: @node %>

<br>

<div>
  <%= link_to "Show this node", @node %> |
  <%= link_to "Back to nodes", nodes_path %>
</div>

app/views/nodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nodes</h1>

<div id="nodes">
  <% @nodes.each do |node| %>
    <%= render node %>
    <p>
      <%= link_to "Show this node", node %>
    </p>
  <% end %>
</div>

<%= link_to "New node", new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render "form", node: @node %>

<br>

<div>
  <%= link_to "Back to nodes", nodes_path %>
</div>

app/views/nodes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @node %>

<div>
  <%= link_to "Edit this node", edit_node_path(@node) %> |
  <%= link_to "Back to nodes", nodes_path %>

  <%= button_to "Destroy this node", @node, method: :delete %>
</div>